server:
  grpc_port: :50051
  http_port: :8080

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: auth_db
  sslmode: disable

jwt:
  secret: your-secret-key
  expiration: 24h